'use client'

import { useState } from 'react'
import { BrainCircuit, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { AiEstimateBadge } from '@/components/dashboard/ai-estimate'
import { notify } from '@/components/ui/toast'

interface Analysis {
  summary: string
  strengths: string[]
  weaknesses: string[]
  next_steps: string[]
  projected_score?: number
  simulated: boolean
}

/**
 * Narrative reading of the student's own statistics.
 *
 * The numbers are computed by the rules engine; the model only explains them.
 * Nothing here is written back to the progress tables.
 */
export function ProgressAnalysis() {
  const [loading, setLoading] = useState(false)
  const [analysis, setAnalysis] = useState<Analysis | null>(null)

  async function run() {
    setLoading(true)
    try {
      const response = await fetch('/api/ai/progress-analysis', { method: 'POST' })
      const payload = await response.json()
      if (!response.ok) {
        notify.error('Could not generate the analysis', payload.error)
        return
      }
      setAnalysis(payload.data as Analysis)
    } catch {
      notify.error('Could not generate the analysis', 'Check your connection and try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="surface-card p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <h3 className="flex items-center gap-2 text-sm font-semibold text-navy-900">
            <BrainCircuit className="size-4 text-brand-600" aria-hidden />
            Study analysis
          </h3>
          <p className="mt-1.5 max-w-lg text-sm text-ink-500">
            A written read of your own numbers: where you are strong, what is holding your overall score
            down, and what to do about it in the next two weeks.
          </p>
        </div>
        <Button onClick={run} disabled={loading} size="sm">
          {loading ? <Loader2 className="animate-spin" aria-hidden /> : null}
          {loading ? 'Analysing…' : analysis ? 'Regenerate' : 'Generate analysis'}
        </Button>
      </div>

      {analysis ? (
        <div className="mt-5 space-y-5 border-t border-hairline pt-5">
          <p className="text-sm leading-relaxed text-ink-700">{analysis.summary}</p>

          {typeof analysis.projected_score === 'number' ? (
            <div className="flex items-center gap-4 rounded-xl bg-brand-50/60 p-4">
              <div>
                <p className="text-xs text-ink-500">Projected score if you keep this up</p>
                <p className="mt-1 text-2xl font-semibold text-navy-900 tabular">
                  {analysis.projected_score}
                </p>
              </div>
              <AiEstimateBadge className="ml-auto" />
            </div>
          ) : null}

          <div className="grid gap-5 sm:grid-cols-2">
            <Column title="Strengths" items={analysis.strengths} />
            <Column title="Holding you back" items={analysis.weaknesses} />
          </div>

          {analysis.next_steps.length > 0 ? (
            <div className="rounded-xl border border-hairline p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">Next steps</p>
              <ol className="mt-2.5 space-y-2">
                {analysis.next_steps.map((step, index) => (
                  <li key={index} className="flex gap-2.5 text-sm leading-relaxed text-ink-600">
                    <span className="grid size-5 shrink-0 place-items-center rounded-full bg-brand-600 text-[10px] font-bold text-white">
                      {index + 1}
                    </span>
                    {step}
                  </li>
                ))}
              </ol>
            </div>
          ) : null}

          {analysis.simulated ? (
            <p className="rounded-lg bg-ink-100 p-3 text-xs text-ink-600">
              Generated by the built-in simulated analyser rather than a live AI provider.
            </p>
          ) : null}
        </div>
      ) : null}
    </div>
  )
}

function Column({ title, items }: { title: string; items: string[] }) {
  if (items.length === 0) return null
  return (
    <div>
      <p className="text-xs font-semibold uppercase tracking-wide text-ink-400">{title}</p>
      <ul className="mt-2 space-y-1.5">
        {items.map((item, index) => (
          <li key={index} className="text-sm leading-relaxed text-ink-600">
            {item}
          </li>
        ))}
      </ul>
    </div>
  )
}
