import { LegalPage, LegalSection } from '@/components/marketing/prose'
import { pageMetadata } from '@/lib/metadata'
import { contactInfo, siteConfig } from '@/lib/site'

export const metadata = pageMetadata({
  title: 'AI Disclaimer',
  description:
    'How Globify PTE Premium generates AI estimated scores, what they are for, and why they are not official Pearson PTE results.',
  path: '/ai-disclaimer',
})

export default function AiDisclaimerPage() {
  return (
    <LegalPage
      title="AI Disclaimer"
      updatedAt="2026-08-13"
      intro="This page explains exactly what our AI scoring does, what it does not do, and how you should use it in your preparation."
    >
      <LegalSection heading="Scores are estimates, not official results">
        <p>
          Every score produced by {siteConfig.product} is labelled an <strong>AI Estimated Score</strong>. It is
          generated by automated systems for study purposes only. It is not an official Pearson PTE score, it
          carries no weight with any institution, and it cannot be submitted anywhere as evidence of English
          proficiency.
        </p>
        <p>
          {siteConfig.company} is not affiliated with, endorsed by, sponsored by, or otherwise connected to Pearson
          Education Ltd or the PTE Academic test. All trademarks belong to their respective owners.
        </p>
      </LegalSection>

      <LegalSection heading="How scoring works">
        <ul>
          <li>
            <strong>Objective tasks</strong> — multiple choice, re-order paragraphs, fill in the blanks, highlight
            incorrect words and write from dictation are marked by deterministic rules that follow the published
            PTE partial-credit conventions. No AI model is involved.
          </li>
          <li>
            <strong>Speaking tasks</strong> — your recording is transcribed and the transcript, the task and the
            expected response are sent to a language model, which returns a structured score across content,
            pronunciation, fluency, grammar and vocabulary.
          </li>
          <li>
            <strong>Writing tasks</strong> — your response and the task requirements are sent to a language model,
            which returns a structured score across content, form, grammar, vocabulary, coherence and development.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="Known limitations">
        <ul>
          <li>
            Pronunciation and fluency are inferred largely from the transcript, hesitation markers and recording
            length. This is a useful signal but it is not the acoustic analysis Pearson performs.
          </li>
          <li>
            Language models are probabilistic. The same response scored twice may not produce identical numbers.
          </li>
          <li>
            Scores are calibrated to be realistic, not generous. Treat a Globify estimate as a directional guide and
            trend line, not a prediction of your exam-day result.
          </li>
          <li>
            When no AI provider is configured, or when a provider is unavailable, the platform falls back to a
            clearly labelled simulated scorer so your practice is not lost. Simulated results are heuristic and are
            marked as such wherever they appear.
          </li>
        </ul>
      </LegalSection>

      <LegalSection heading="Your data and AI providers">
        <p>
          To score a response we send the task, your written response or transcript, and your target score to the
          configured AI provider. We do not send your name, email address or any other identifying detail. Audio
          recordings are stored privately and served only through short-lived signed URLs.
        </p>
        <p>
          You can request deletion of your recordings and responses at any time from your profile, or by writing to{' '}
          <a href={`mailto:${contactInfo.supportEmail}`}>{contactInfo.supportEmail}</a>.
        </p>
      </LegalSection>

      <LegalSection heading="Human review">
        <p>
          On plans that include it, you can request a teacher review of any response. A Globify teacher then adds
          their own score and corrections alongside the AI estimate. Where a teacher score exists, it is displayed
          as the authoritative one.
        </p>
      </LegalSection>
    </LegalPage>
  )
}
